name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: ./test.sh

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Final message
        run: echo "Pipeline complet OK"
